# Simple workflow for deploying static content to GitHub Pages
name: Deploy

on:
  push:
    branches:
      - main


jobs:
  # Single deploy job since we're just deploying
  build:  
    name: Build
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with: 
          node-version: 18.16.0
          
      - uses: pnpm/action-setup@v2
        with:
          version: 8.3.1
      - name: Install dependencies
        run: pnpm install
        
      - name: build project
        run: pnpm run build
        
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist